<?php

namespace Database\Seeders;

use App\Models\Word;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class WordSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $palabras = [
            "casa", "mesa", "silla", "flor", "sol", "luz", "pan", "perro", "gato", "niño",
            "agua", "nube", "libro", "verde", "rojo", "fruta", "pared", "piso", "papel", "tren",
            "camión", "coche", "moto", "radio", "fuego", "humo", "llama", "playa", "arena", "lago",
            "pato", "pez", "ratón", "tele", "carta", "mano", "brazo", "pie", "dedo", "zapato",
            "camisa", "pantalón", "chaqueta", "cuerda", "pluma", "lluvia", "nieve", "globo", "aire", "taza",
            "vaso", "leche", "vino", "queso", "miel", "dulce", "tigre", "oso", "zorro", "piedra",
            "puerta", "ventana", "techo", "cielo", "estrella", "luna", "mar", "barco", "avión", "rueda",
            "motor", "caja", "bote", "jugo", "lima", "pera", "uva", "plátano", "limón", "manzana",
            "melón", "sandía", "kiwi", "hoja", "rama", "tronco", "árbol", "bosque", "campo", "camino",
            "puente", "reloj", "bolso", "lápiz", "goma", "regla", "saco", "mochila", "foto", "mapa",
            "cuadro", "juego", "puzzle", "clase", "botón", "cable", "llave", "sombrero", "bufanda", "guante",
            "abrigo", "llanto", "risa", "cara", "ojo", "boca", "nariz", "diente", "cola", "pelo",
            "ceja", "frente", "codo", "talón", "rodilla", "espalda", "pecho", "barriga", "corazón", "baño",
            "ducha", "espejo", "toalla", "pasta", "jabón", "champú", "lavabo", "cama", "almohada", "sábana",
            "manta", "colchón", "bombilla", "ventilador", "cerradura", "pasillo", "escalera", "ascensor", "cocina", "fregadero",
            "horno", "sartén", "cuchara", "tenedor", "cuchillo", "plato", "comida", "cena", "desayuno", "merienda",
            "juguete", "pelota", "muñeca", "oso", "cubo", "pala", "parque", "columpio", "tobogán", "hierba",
            "madera", "tierra", "grillo", "rana", "cebra", "abeja", "mosca", "gallo",
            "gamba", "pasto", "ramas", "nidos", "cabra", "burro", "trigo", "grano", "grasa",
            "sopa", "café", "plomo", "plata", "dardo", "flecha", "arco", "roca",
            "pico", "cima", "loma", "pampa", "isla", "océano", "gafas", "lente", "verbo", "letra",
            "sílaba", "punto", "frase", "texto", "cuento", "poema", "rima", "canto", "voz", "sonido",
            "timbre", "claxon", "silencio", "eco", "palabra", "lengua", "idioma", "dicho", "fraseo",
            "traje", "corbata", "falda", "chaleco", "calzado", "tenis", "botas", "guantes", "gorro", "pañuelo",
            "anillo", "pulsera", "collar", "arete", "broche", "sombrilla", "carro", "taxi",
            "metro", "bicicleta", "patín", "balsa", "escritorio", "pizarra",
            "tiza", "marcador", "escuadra", "cartel", "enchufe", "teclado",
            "pantalla", "monitor", "router", "wifi", "teléfono", "celular", "móvil", "tablet",
            "agenda", "libreta", "cuaderno", "página", "carpeta", "archivo", "ficha",
            "sofá", "lámpara", "cortina", "alfombra",
            "colcha", "cobija", "edredón", "bañera", "esponja",
            "cepillo", "peine", "secador", "crema", "colonia", "perfume", "cuchilla", "espuma",
            "microondas", "olla", "botella", "copa", "jarra", "tetera", "azucarera", "salero", "pimentero", "panera",
            "cereal", "galleta", "yogur", "manteca", "mantequilla", "nata", "huevo", "pollo",
            "carne", "pescado", "atún", "salmón", "bacalao", "paella", "ensalada", "puré", "tortilla",
            "arroz", "bollito", "bizcocho", "tarta", "flan", "helado", "chocolate", "caramelo", "gominola",
            "fresa", "naranja", "mandarina",
            "piña", "cereza", "ciruela", "granada", "mango", "papaya", "guayaba", "coco", "frambuesa",
            "murciélago", "escalpelo", "cauterio", "albahaca", "cóndor", "alquimia", "bisel", "cántaro", "candelabro", "candelilla",
            "cántico", "alquimista", "bifurcación", "cincel", "dédalo", "efeméride", "filigrana", "gárgola", "hálito", "ignífugo",
            "jadeante", "kilómetro", "lánguido", "madriguera", "nácar", "óxido", "péndulo", "quimera", "resiliencia", "sagaz",
            "tácito", "ubérrimo", "vástago", "xilófono", "yacimiento", "zángano", "abedul", "bambú", "cactus", "dátil",
            "ebrio", "fábula", "gacela", "hiena", "impulso", "jade", "koala", "lince", "morsa", "nuez",
            "orquídea", "papiro", "quinto", "ruiseñor", "sándalo", "tapiz", "uña", "vicuña", "wafle", "xerófilo",
            "yegua", "zafiro", "acacia", "bisonte", "cólera", "dócil", "ébano", "fénix", "góndola", "horizonte",
            "índigo", "jengibre", "kárate", "lámpara", "mástil", "náusea", "ópera", "píxel", "quiosco", "rótulo",
            "sótano", "tótem", "ulular", "vórtice", "whisky", "xenón", "yogur", "zodiaco", "alondra", "bóveda",
            "cúpula", "dólar", "éxodo", "fósil", "gólem", "hongo", "ícono", "jilguero", "kiosco", "lóbrego",
            "músculo", "nómada", "óvalo", "pólvora", "quasar", "réquiem", "sístole", "tímpano", "úlcera", "vértigo",
            "watt", "yunque", "zurrón", "alquitrán", "bóxer", "éxito", "fórmula", "héroe", "ítem", "kilovatio",
            "lúgubre", "módulo", "óptica", "píldora", "quimono", "régimen", "súbdito", "tóxico", "único",
            "abismo", "acertijo", "adivinanza", "aeropuerto", "aguijón", "alambique", "alborada", "alfiler", "alga", "aliento",
            "almendra", "altavoz", "amapola", "amuleto", "ancla", "andén", "ángulo", "antena", "antídoto", "anzuelo",
            "aplauso", "araña", "arcilla", "arenal", "arista", "armadura", "aroma", "arpón", "asfalto", "astilla",
            "atún", "avellana", "azulejo", "bache", "bacteria", "bahía", "balanza", "balsa", "bambalina", "banco",
            "bandada", "bandera", "banquillo", "baranda", "barro", "bastón", "batuta", "bisonte", "blusa", "bodega",
            "borrasca", "botiquín", "brasa", "brújula", "bufón", "buitre", "burbuja", "cabestro", "cabina", "cable",
            "cactus", "cadencia", "calabaza", "caldera", "califa", "callejón", "calor", "calumnia", "camarote", "camello",
            "camilla", "campana", "canario", "canasta", "candado", "canica", "canoa", "cántaro", "capullo", "caracola",
            "carambola", "caravana", "carcaj", "caricia", "carnaval", "carpa", "carreta", "carroza", "cartucho", "casco",
            "castaña", "castillo", "catalejo", "caverna", "cazuela", "cebolla", "cedro", "celda", "celosía", "ceniza",
            "cerilla", "cerradura", "cetro", "chacal", "chaleco", "charco", "chatarra", "chequera", "chicle", "chimenea",
            "chirimoya", "chispa", "chopo", "chorro", "chuleta", "ciclón", "cigarra", "cilindro", "cinta", "ciruela",
            "cisne", "claraboya", "clavel", "claxon", "cloaca", "cobertizo", "cobre", "cocodrilo", "codo", "colmena",
            "coloso", "columna", "cometa", "compás", "concha", "consola", "contrabajo", "coral", "corchea", "corneta",
            "corona", "corral", "correa", "cosecha", "costilla", "cráneo", "cráter", "cremallera", "crisol", "crucigrama",
            "cuaderno", "cuadro", "cuenca", "cueva", "cuerda", "culebra", "culote", "cupón", "curva", "daga",
            "dalila", "danza", "dardo", "debate", "dedal", "defensa", "delantal", "delirio", "delta", "dentadura",
            "depósito", "deriva", "desván", "diadema", "diamante", "diapasón", "dibujo", "diente", "dique", "disfraz",
            "diván", "doblón", "doquier", "dragón", "driza", "duende", "dulzura", "ebriedad", "eco", "edén",
            "efluvio", "egida", "ejote", "elipse", "emblema", "emulsión", "enigma", "ensayo", "entresuelo", "envase",
            "epopeya", "equino", "erizo", "escama", "escapulario", "escarcha", "escena", "esclava", "escoba", "escopeta",
            "esfera", "esmalte", "espejismo", "espina", "esquimal", "estaca", "estambre", "estanque", "estepa", "estilete",
            "estuche", "etéreo", "eufonía", "euforia", "exilio", "fábula", "fachada", "falda", "fanal", "fango",
            "fantasma", "farol", "faro", "fauces", "felpa", "feria", "fideo", "fiera", "figura", "filo",
            "flauta", "fleco", "florero", "flota", "foco", "fogata", "folleto", "forja", "fortaleza", "fosfato",
            "fragancia", "franja", "frasco", "fronda", "fruta", "fuelle", "funda", "fusil", "gaceta", "galaxia",
            "galera", "galpón", "gamuza", "garra", "gasa", "gaviota", "gemelo", "genciana", "girasol", "glaciar",
            "globo", "gobernalle", "goloso", "góndola", "gorra", "gorro", "gota", "grada", "granada", "grano",
            "grifo", "grúa", "guante", "guarida", "guijarro", "guitarra", "gusano", "haba", "hacha", "halcón",
            "hamaca", "harina", "haz", "helecho", "helio", "heraldo", "herradura", "hiedra", "higo", "hilera",
            "hilo", "hoguera", "hormiga", "horno", "hueso", "huésped", "humo", "huracán", "icono", "idea",
            "ídolo", "iglesia", "iguana", "ilusión", "imán", "imperio", "incendio", "índice", "infierno", "ingenio",
            "insecto", "instinto", "intemperie", "invierno", "isla", "jabón", "jade", "jaguar", "jamón", "jarabe",
            "jardín", "jaula", "jazmín", "jengibre", "jerga", "jinete", "jirafa", "jofaina", "jolgorio", "jornada",
            "joya", "judía", "juguete", "jungla", "junquillo", "junta", "júpiter", "justicia", "labrador", "ladera",
            "ladrillo", "lagarto", "lágrima", "laguna", "lámpara", "lancha", "lápiz", "largo", "lata", "lazo",
            "lechuza", "legumbre", "león", "leopardo", "liana", "libélula", "lienzo", "ligero", "limón", "lince",
            "lira", "lobo", "loma", "lomo", "losa", "luciérnaga", "lugar", "lupa", "luz", "maceta",
            "acuario", "bisonte", "cascada", "dromedario", "esmalte", "flauta", "gaceta", "horizonte", "incendio", "jirafa",
            "kilogramo", "luciérnaga", "mandarina", "nave", "orilla", "papiro", "quesería", "ruiseñor", "sándalo", "tapiz",
            "uña", "vicuña", "wafle", "xerófilo", "yegua", "zafiro", "abedul", "bambú", "cactus", "dátil",
            "ebrio", "fábula", "gacela", "hiena", "impulso", "jade", "koala", "lince", "morsa", "nuez",
            "orquídea", "papiro", "quinto", "ruiseñor", "sándalo", "tapiz", "uña", "vicuña", "wafle", "xerófilo",
            "yegua", "zafiro", "acacia", "bisonte", "cólera", "dócil", "ébano", "fénix", "góndola", "horizonte",
            "índigo", "jengibre", "kárate", "lámpara", "mástil", "náusea", "ópera", "píxel", "quiosco", "rótulo",
            "sótano", "tótem", "ulular", "vórtice", "whisky", "xenón", "yogur", "zodiaco", "alondra", "bóveda",
            "cúpula", "dólar", "éxodo", "fósil", "gólem", "hongo", "ícono", "jilguero", "kiosco", "lóbrego",
            "músculo", "nómada", "óvalo", "pólvora", "quasar", "réquiem", "sístole", "tímpano", "úlcera", "vértigo",
            "watt", "yunque", "zurrón", "alquitrán", "bóxer", "éxito", "fórmula", "héroe", "ítem", "kilovatio",
            "lúgubre", "módulo", "óptica", "píldora", "quimono", "régimen", "súbdito", "tóxico", "único",
            "abismo", "acertijo", "adivinanza", "aeropuerto", "aguijón", "alambique", "alborada", "alfiler", "alga", "aliento",
            "almendra", "altavoz", "amapola", "amuleto", "ancla", "andén", "ángulo", "antena", "antídoto", "anzuelo",
            "aplauso", "araña", "arcilla", "arenal", "arista", "armadura", "aroma", "arpón", "asfalto", "astilla",
            "atún", "avellana", "azulejo", "bache", "bacteria", "bahía", "balanza", "balsa", "bambalina", "banco",
            "bandada", "bandera", "banquillo", "baranda", "barro", "bastón", "batuta", "bisonte", "blusa", "bodega",
            "borrasca", "botiquín", "brasa", "brújula", "bufón", "buitre", "burbuja", "cabestro", "cabina", "cable",
            "cactus", "cadencia", "calabaza", "caldera", "califa", "callejón", "calor", "calumnia", "camarote", "camello",
            "camilla", "campana", "canario", "canasta", "candado", "canica", "canoa", "cántaro", "capullo", "caracola",
            "carambola", "caravana", "carcaj", "caricia", "carnaval", "carpa", "carreta", "carroza", "cartucho", "casco",
            "castaña", "castillo", "catalejo", "caverna", "cazuela", "cebolla", "cedro", "celda", "celosía", "ceniza",
            "cerilla", "cerradura", "cetro", "chacal", "chaleco", "charco", "chatarra", "chequera", "chicle", "chimenea",
            "chirimoya", "chispa", "chopo", "chorro", "chuleta", "ciclón", "cigarra", "cilindro", "cinta", "ciruela",
            "cisne", "claraboya", "clavel", "claxon", "cloaca", "cobertizo", "cobre", "cocodrilo", "codo", "colmena",
            "coloso", "columna", "cometa", "compás", "concha", "consola", "contrabajo", "coral", "corchea", "corneta",
            "corona", "corral", "correa", "cosecha", "costilla", "cráneo", "cráter", "cremallera", "crisol", "crucigrama",
            "cuaderno", "cuadro", "cuenca", "cueva", "cuerda", "culebra", "culote", "cupón", "curva", "daga",
            "dalila", "danza", "dardo", "debate", "dedal", "defensa", "delantal", "delirio", "delta", "dentadura",
            "depósito", "deriva", "desván", "diadema", "diamante", "diapasón", "dibujo", "diente", "dique", "disfraz",
            "diván", "doblón", "doquier", "dragón", "driza", "duende", "dulzura", "ebriedad", "eco", "edén",
            "efluvio", "egida", "ejote", "elipse", "emblema", "emulsión", "enigma", "ensayo", "entresuelo", "envase",
            "epopeya", "equino", "erizo", "escama", "escapulario", "escarcha", "escena", "esclava", "escoba", "escopeta",
            "esfera", "esmalte", "espejismo", "espina", "esquimal", "estaca", "estambre", "estanque", "estepa", "estilete",
            "estuche", "etéreo", "eufonía", "euforia", "exilio", "fábula", "fachada", "falda", "fanal", "fango",
            "fantasma", "farol", "faro", "fauces", "felpa", "feria", "fideo", "fiera", "figura", "filo",
            "flauta", "fleco", "florero", "flota", "foco", "fogata", "folleto", "forja", "fortaleza", "fosfato",
            "fragancia", "franja", "frasco", "fronda", "fruta", "fuelle", "funda", "fusil", "gaceta", "galaxia",
            "galera", "galpón", "gamuza", "garra", "gasa", "gaviota", "gemelo", "genciana", "girasol", "glaciar",
            "globo", "gobernalle", "goloso", "góndola", "gorra", "gorro", "gota", "grada", "granada", "grano",
            "grifo", "grúa", "guante", "guarida", "guijarro", "guitarra", "gusano", "haba", "hacha", "halcón",
            "hamaca", "harina", "haz", "helecho", "helio", "heraldo", "herradura", "hiedra", "higo", "hilera",
            "hilo", "hoguera", "hormiga", "horno", "hueso", "huésped", "humo", "huracán", "icono", "idea",
            "ídolo", "iglesia", "iguana", "ilusión", "imán", "imperio", "incendio", "índice", "infierno", "ingenio",
            "insecto", "instinto", "intemperie", "invierno", "isla", "jabón", "jade", "jaguar", "jamón", "jarabe",
            "jardín", "jaula", "jazmín", "jengibre", "jerga", "jinete", "jirafa", "jofaina", "jolgorio", "jornada",
            "joya", "judía", "juguete", "jungla", "junquillo", "junta", "júpiter", "justicia", "labrador", "ladera",
            "ladrillo", "lagarto", "lágrima", "laguna", "lámpara", "lancha", "lápiz", "largo", "lata", "lazo",
            "lechuza", "legumbre", "león", "leopardo", "liana", "libélula", "lienzo", "ligero", "limón", "lince",
            "lira", "lobo", "loma", "lomo", "losa", "luciérnaga", "lugar", "lupa", "luz", "maceta",
        ];

        foreach ($palabras as $palabra) {
            Word::create(['word' => $palabra]);
        }
    }
}
