version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: one_click_container
    volumes:
      - ../..:/workspaces:cached
    ports:
      - "8000:8000"   # Laravel backend
      - "5173:5173"   # Vue frontend
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:16
    container_name: postgres_oc
    restart: unless-stopped
    environment:
      POSTGRES_USER: oneclick
      POSTGRES_PASSWORD: oneclick
      POSTGRES_DB: oneclick_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_oc
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"     # Accede a pgAdmin en http://localhost:5050
    depends_on:
      - postgres
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
